spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sirumatek
    username: root
    password: "basededatos1$"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hikari:
    maximum-pool-size: 10
    connection-timeout: 20000
    idle-timeout: 30000
    max-lifetime: 1800000
  jwt:
    secret_key: "123456789"